version: "3.1"

services:
  dbmysql:
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: skillsharePassword
      MYSQL_DATABASE: skillshare_db
      MYSQL_USER: skillshare_admin
      MYSQL_PASSWORD: skillsharePassword
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
