version: "3.1"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skillshare_admin
      POSTGRES_PASSWORD: skillsharePassword
      PP_DB_NAME: skillshare_db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
